version: "3.8"

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    container_name: my-zookeeper
    image: bitnami/zookeeper:3.7
    networks:
      - kafka-net
    ports:
      - "2182:2182"   # 2181 port는 HBase의 zookeeper가 사용하므로 2182 포트 사용
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    container_name: my-kafka
    image: bitnami/kafka:3
    networks:
      - kafka-net
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2182
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper