version: "3"
services:
  server1:
    image: ubuntu:latest
    ports:
      - "8083:8083"
    stdin_open: true
    tty: true

    volumes:
      - C:\Users\fora2\OneDrive\Project\eCommerce_behavior_data_pipeline:/home
  server2:
    image: ubuntu:latest
    ports:
      - "8084:8084"
    stdin_open: true
    tty: true